language: elixir

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.2.6
    - otp_release: 18.3
      elixir: 1.3.4
    - otp_release: 19.0
      elixir: 1.3.4
    - otp_release: 19.0
      elixir: 1.4.0

sudo: false
notifications:
  recipients:
    - skipper199202@gmail.com
before_script:
  - mix deps.get --only test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
