language: elixir
elixir:
  - 1.3.2
otp_release:
  - 19.0
addons:
  postgresql: '9.4'
services:
  - postgresql
  - redis-server
sudo: false
before_script:
  - mix deps.get --only test
  - nvm install 6.2 && nvm use 6.2
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
script:
  - mix test --exclude integration
  - cd installer && mix test
  - cd ../ && npm install && npm test
after_script:
  - cd $TRAVIS_BUILD_DIR
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
